// apps/vue3/src/App.vue
<!--
 * @Author: your name
 * @Date: 2020-12-03 19:16:25
 * @LastEditTime: 2020-12-03 20:07:53
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/CompileVueWithReact/apps/vue3/src/App.vue
-->
<template>
  <div>
    <Count />
    <DoubleCount />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Count from './components/Count/index.vue'
import DoubleCount from './components/DoubleCount/index.vue'

export default defineComponent({
  name: 'App',
  components: {
    Count,
    DoubleCount
  }
})
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// src/react-app/index.tsx
/*
 * @Author: your name
 * @Date: 2020-12-02 13:46:38
 * @LastEditTime: 2020-12-03 14:12:59
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/vue-react/index.js
 */

import React from 'react'
import ReactDOM from 'react-dom'
import Other from './Other'


const CreateReactApp = () => ReactDOM.render(
  <Other />, document.getElementById('root')
)

export default CreateReactApp
