// src/vue-app/Other.vue
<!--
 * @Author: your name
 * @Date: 2020-12-02 22:27:35
 * @LastEditTime: 2020-12-03 14:10:31
 * @LastEditors: your name
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/CompileVueWithReact/src/vue-app/Other.vue
-->
<template>
  <div>
    It is vue，current Count is <span :class="styles.count">{{ count }}</span>
  </div>
</template>
<script>
import styles from './style.module.scss'

export default {
  name: "Count",
  data() {
    return {
      count: 0,
      styles
    }
  },
  mounted() {
    const _this = this
    this.timer = setInterval(() => {
      _this.count = Math.floor(Math.random(0, 1) * 100)
    }, 600)
  },
  beforeDestroy() {
    clearInterval(this.timer)
  }
}
</script>

// src/react-app/Other.jsx
/*
 * @Author: your name
 * @Date: 2020-12-02 13:50:31
 * @LastEditTime: 2020-12-03 15:30:25
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/vue-react/other.js
 */

import React, { useEffect, useState } from 'react'
import styles from './style.module.scss'

const Other = () => {
  const [count, setCount] = useState(0)
  useEffect(() => {
    const timer = setTimeout(() => {
      const c = Math.floor(Math.random() * 100)
      setCount(c)
    }, 600)
    return () => {
      clearTimeout(timer)
    }
  })
  return (
    <h2>
      It is React, current Count is&nbsp;
      <span className={styles.count}>{ count }</span>
    </h2>
  )
}
export default Other
