// apps/vue3/src/App.vue
<!--
 * @Author: your name
 * @Date: 2020-12-03 19:16:25
 * @LastEditTime: 2020-12-03 20:07:53
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/CompileVueWithReact/apps/vue3/src/App.vue
-->
<template>
  <div>
    <Count />
    <DoubleCount />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Count from './components/Count/index.vue'
import DoubleCount from './components/DoubleCount/index.vue'

export default defineComponent({
  name: 'App',
  components: {
    Count,
    DoubleCount
  }
})
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// apps/react17/src/App.tsx
/*
 * @Author: your name
 * @Date: 2020-12-04 09:34:47
 * @LastEditTime: 2020-12-04 10:50:46
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /MyNote/CompileVueWithReact/apps/react17/src/App.js
 */
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import store from './redux/store/index'

import First from '@src/page/First/index'

const App = () => {
  return (
    <Provider store={store} >
      <First />
    </Provider>
  )
}

ReactDOM.render(<App />, document.getElementById('RootReact'))
